CREATE TABLE sales_incremental (
    ORDERNUMBER INT PRIMARY KEY,
    QUANTITYORDERED INT,
    PRICEEACH FLOAT,
    SALES FLOAT,
    ORDERDATE VARCHAR(50),
    STATUS VARCHAR(50),
    PRODUCTLINE VARCHAR(100),
    COUNTRY VARCHAR(100)
);


CREATE TABLE watermark_table (
    last_order_number INT
);

INSERT INTO watermark_table VALUES (0);
